### ISSUE TITLE
Выделить интерфейсы

### ISSUE THREAD

**Issue by anry-das** [alinashev/NCLab2#11]
Для всех классов, которые инжектятся (как минимум), необходимо создать интерфейсы.
При нжекте используется именно интерфейс.

**Comment by alinashev** [comment]
10149c8

**Comment by anry-das** [comment]
А при инжекте используются интерфейсы?

**Comment by alinashev** [comment]
> А при инжекте используются интерфейсы?

Исправила, теперь думаю правильно
