### ISSUE TITLE
Неправильное использование DI

### ISSUE THREAD

**Issue by anry-das** [alinashev/NCLab2#2]
При DI не используют оператор new. Созданием бинов занимается Spring
Поэтому вот такие вызовы
```
private Writer writer = new Writer();
private AsyncRunner asyncRunner = new AsyncRunner();
```
необходимо заменить на
```
@Autowired
private Writer writer;
@Autowired
private AsyncRunner asyncRunner;
```
Также необходимо для всех классов (бинов), для которых используется DI, выделить интерфейсы и при инжекте использовать именно инт-сы.

**Comment by alinashev** [comment]
5a78875
